<?php
namespace jakharbek\menu\modules\menu\components;

use jakharbek\menu\models\MenuItemsForm;
use Yii;
use jakharbek\menu\components\MenuRender;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use jakharbek\menu\models\Menu;
use jakharbek\menu\models\MenuItems;
use yii\widgets\Pjax;

class MenuAdmin extends MenuRender{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

$js = <<<JS
  $(function  () {
  $("ol.menu-admin").sortable({
  
      handle: '.menu-item-title',
      onDrop: function(item, container, _super) {
        _super(item, container); 
        var index = $(item).index() + 1;
        var element_id = $(item).attr("menuitem-id");
        var parent = $(item).parents()[1];
        console.log(parent);
        var parent_id = $(parent).attr("menuitem-id");
            $.ajax({
            'type' : 'POST',
            'data' : 'menuItemUpdate=ok&id=' + element_id + '&sort='+index +'&parent='+parent_id,
            'url' : window.location.href,
            'success' : function(data){
                console.log(data); 
                  $('.menu-admin li').each(function(index,itemli){
                        var index = $(itemli).index() + 1;
                        var element_id = $(itemli).attr("menuitem-id");
                        var parent = $(itemli).parents()[1];
                        var parent_id = $(parent).attr("menuitem-id");      
                          $.ajax({
                            'type' : 'POST',
                            'data' : 'menuItemUpdate=ok&id=' + element_id + '&sort='+index +'&parent='+parent_id,
                            'url' : window.location.href,
                            });
                  });
            }
            });
      },
  });
  $('.menu-item-get-settings').click(function(e){
     var parent = $(this).parents("li");
     var menu_id = parent.attr('menuitem-id');
     $('.menu-item-settings[menuitem-id='+menu_id+']').toggle();
  });
}); 
JS;

$css = <<<CSS
body.dragging, body.dragging * {
  cursor: move !important;
}
.dragged {
  position: absolute;
  opacity: 0.5;
  z-index: 2000;
}
ol.menu-admin li.placeholder {
  position: relative;
  /** More li styles **/
}
ol.menu-admin li.placeholder:before {
  position: absolute;
  /** Define arrowhead **/
}
.menu-admin li{
   padding:5px 10px;
   list-style: none;
    color: #23282d;
    cursor: move;    
    width:450px; 
    padding-bottom:0px;
}
.menu-admin li .menu-item{ 
    overflow: hidden;
    padding: 10px 10px;
    min-height: 40px;
    border: 1px solid #ddd;
    position: relative;
    height: auto;
    word-wrap: break-word;
    line-height: 20px;
    font-weight: 600;
    background: #f5f5f5;
}
.menu-admin li .menu-item .menu-item-title{
    float:left;
    width:80%;
}
.menu-admin li .menu-item-settings{
    background: #f5f5f5;
    display: none;
    padding:10px 10px;
}
.menu-admin li .menu-item .menu-item-right-block{
    float:right;
    cursor: pointer;
    font-size:18px;
}
.menu-admin{
 
}
CSS;

        Yii::$app->view->registerJs($js);
        Yii::$app->view->registerCss($css);
    }

    public function beforeRenderMenu()
    {
        echo '<ol class="menu-admin">';
    }

    public function afterRenderMenu()
    {
        echo '</ol>';
    }

    public function beginRenderItem()
    {
        if($this->has_child):
            echo '<li menuitem-id="'.$this->item->id.'">';
            echo "<div class='menu-item'>";
                echo '<div  class="menu-item-title"> ';
                    echo $this->item->title;
                echo "</div>";
                echo '<div  class="menu-item-right-block"> ';
                    echo '<span class="glyphicon glyphicon-collapse-down menu-item-get-settings"></span>';
                echo "</div>";
            echo '</div>';
            $this->menuItemSetting();

        else:
            echo '<li menuitem-id="'.$this->item->id.'">';
            echo "<div class='menu-item'>";
                    echo '<div  class="menu-item-title"> ';
                        echo $this->item->title;
                    echo "</div>";
                    echo '<div  class="menu-item-right-block"> ';
                        echo '<span class="glyphicon glyphicon-collapse-down menu-item-get-settings"></span>';
                    echo "</div>";
                echo '</div>';
            $this->menuItemSetting();
            echo "<ol>";
        endif;

    }
    private function menuItemSetting(){
        $model = new MenuItemsForm(['scenario' => MenuItems::SCENARIO_UPDATE,'id' => $this->item->id]);

        echo '<div  class="menu-item-settings" menuitem-id="'.$this->item->id.'"> ';
            $form = ActiveForm::begin(['id' => 'menu-item-form','options' => ['data-pjax' => true,['enctype' => 'multipart/form-data']]]);
            echo $form->field($model,'title');
            echo $form->field($model,'url');
            echo $form->field($model,'icon');
            echo $form->field($model,'imageFile')->fileInput();
            echo Html::img($this->item->getImageLink(),['class' => 'col-md-12 col-xs-12 col-lg-12 ','style' => 'padding:5px;']);
        echo $form->field($model,'id')->hiddenInput()->label(false);
            echo Html::submitButton(Yii::t('jakhar-menu','Menu Update'),['class' => 'btn btn-primary']);

        echo Html::a(Yii::t('jakhar-menu','Menu Remove'),'#menuitem',['class' => 'btn btn-danger pull-right',
            'title'        => 'delete',
            'data-query' => 'delete',
            'data-query-delete-selector' => 'li[menuitem-id='.$this->item->id.']',
            'data-query-method' => 'POST',
            'data-query-url' => yii\helpers\Url::to(["/".Yii::$app->request->pathInfo]),
            'data-query-confirm' => Yii::t('jakhar-menu','Are you sure?'),
            'data-query-params' => 'id='.$this->item->id.'&menuItemDelete=delete']);
            ActiveForm::end();
        echo "</div>";
    }

    public function endRenderItem()
    {
        if($this->has_child):
            echo '</li>';
        else:
            echo '</ol></li>';
        endif;
    }

    public function beginRenderItemChild()
    {
        echo '<li menuitem-id="'.$this->item->id.'">';
        echo "<div class='menu-item'>";
            echo '<div  class="menu-item-title"> ';
                echo $this->item->title;
            echo "</div>";
            echo '<div  class="menu-item-right-block"> ';
                echo '<span class="glyphicon glyphicon-collapse-down menu-item-get-settings"></span>';
            echo "</div>";
        echo '</div>';
        $this->menuItemSetting();
        if(!$this->has_child):
            echo '<ol></ol>';
        endif;
    }

    public function endRenderItemChild()
    {
        echo "</li>";
    }

    public function beforeRenderItemChilds()
    {
        echo "<ol>";
    }

    public function afterRenderItemChilds()
    {
        echo "</ol>";
    }
}