<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Menu Manager' => 'Меню',
    'Menu Item' => 'Элемент меню',
    'Menu' => 'Меню',
    'Menu Structure' => 'Структура меню',
    'Menus' => 'Меню',
    'Menu Create' => 'Создать',
    'Are you sure?' => 'Вы уверены?',
    'Menu Remove' => 'Удалить',
    'Menu Update' => 'Обновить',
    'Unique ID' => 'Уникальный код',
    'Menu ID' => 'Уникальный меню код',
    'Title' => 'Название',
    'Url' => 'Ссылка',
    'Extends' => 'Родительский элемент',
    'Sort' => 'Сортировка',
    'Icon' => 'Иконка',
    'Image' => 'Изображение',
    'imageFile' => 'Изображение',
    'Alias' => 'Алиас',
];
